module.exports = {
  "NAME": "Rbt",
  "ADDRESS": "",
  "INTERVAL_MILLISEC": 60000,
  "RECORDS": ["CSV", "MACHINIST"],
  //"RECORDS": ["CSV", "AMBIENT"]
  //"RECORDS": ["CSV", "MACHINIST", "AMBIENT],
  "MACHINIST_API_KEY": "",
  "MACHINIST_MULTIPLE": 1
  //"AMBIENT_CHANNEL": ,
  //"AMBIENT_WRITE_KEY": "",
  //"AMBIENT_MULTIPLE": 1
};
