module.exports = {
  "NAME": "Rbt",
  "ADDRESS": "[YOUR BU01 ADDRESS NO SEMICOLON]",
  "INTERVAL_MILLISEC": 30000,
  "AMBIENT_CHANNEL": '[YOUR AMBIENT CHANNEL ID]',
  "AMBIENT_WRITE_ID": "[YOUR AMBIENT WRITE ID]"
};
