#!/bin/bash

# This shell script is executed by a user manually or another auto installer programs. #

set -eu

if ! [ $(whoami) = root ]; then echo 'Error: root permission required.'; exit 1; fi

ScriptDir=$(cd $(dirname $BASH_SOURCE); pwd)
cd $ScriptDir

# display command options #
if [ $# -gt 0 ] && [ "$1" = '-h' ] ; then
cat <<EOF

- install without any options (default)

- install with following options
   -y (skip confirm (force overwrite if config file is already exists))
   -s filepath (status log file path (default ./status.txt)
   -c filepath (config file path (default ./config.js)

- initialize
   -i initialize (set defalut) env.sh (StatusFile="status.txt", ConfigFile="config.js")

EOF
exit 0
fi

ForceOverwite='no'
while getopts "yis:c:" op
do
    case $op in
        y)
            ForceOverwite='yes'
            ;;
        s)
	    # modify the value of StatusFile in env.sh #
            StatusFile="$OPTARG"
	    sed -i "/^StatusFile=/d" env.sh
	    echo "StatusFile=\"$StatusFile\"" >> env.sh
            ;;
        c)
	    # modify the value of ConfigFile in env.sh #
            ConfigFile="$OPTARG"
	    sed -i '/^ConfigFile=/d' env.sh
	    echo "ConfigFile=\"$ConfigFile\"" >> env.sh
            ;;
	i)
	    # initialize env.sh #
	    cat <<EOF > env.sh
#!/bin/bash

# This shell script is called by install.sh, uninstall.sh, start.sh 
# And generated and modifid by executing install.sh with c,s,i options

Start="start.sh"
CheckConfig="checkConfig.js"
ConfigFile="config.js"
StatusFile="status.txt"
EOF
	    echo "Initialized env.sh, done."
	    . env.sh
	    [ -f $StatusFile ] && rm $StatusFile
	    exit 0
	    ;;
        *)
	    exit 1
            ;;
    esac
done

. env.sh

echo 'install syncLog ...'

ConfFileWrite(){
    cat <<EOF > $ConfigFile
/*
This is syncLog setting file (Javascript source).
Setting is array of objects. 
Followings are example of setting.

module.exports = [
  {
    type: 'rsync',                           //rsync
    intervalHours: 1,                        //execute interval hours
    source: '/home/pi/source_dir/',          //local source directory
    dest: '/boot/data/'                      //local distination directory
  }
  ,
  {
    type: 'rclone',                          //rclone
    intervalHours: 24,                       //execute interval hours
    rcloneConf: '/boot/rclone.conf',         //configuration file generated by rclone
    source: '/boot/data',                    //local directory
    destService: 'gdrive',                   //service name in rclone.conf
    destDir: 'data'                          //folder in cloud service
  }
];
*/

module.exports = [

];

EOF
}

# for interaction #
if [ -f $ConfigFile ] && [ $ForceOverwite != 'yes' ] ; then
    echo "Setting file:${ConfigFile} is already exist, overwrite? (yes|no)"
    echo -n "> "
    read ForceOverwite # read #
    case $ForceOverwite in
	yes)
	    ConfFileWrite
	    ;;
	no)
	    :
	    ;;
	*)
	    echo -e "Cannot understand '$ForceOverwite'.\nInstall fail."
	    exit 1
            ;;
    esac
else ConfFileWrite; fi

# install depend packages #
which nkf > /dev/null || apt install -y nkf
which node > /dev/null || apt install -y nodejs
which rclone > /dev/null || apt install -y rclone

# create systemd service #
cat <<EOF > /etc/systemd/system/syncLog.service
[Unit]
Description=syncLog
After=syslog.target network.target

[Service]
Type=simple
WorkingDirectory=$ScriptDir
ExecStart=/bin/bash -c ": > $StatusFile; ./$Start > $StatusFile 2>&1"
#ExecStop=/bin/bash -c "./$Start -execStop > $StatusFile 2>&1"
User=root
Group=root
StandardOutput=journal
StandardError=journal

[Install]
WantedBy = multi-user.target

EOF

#systemctl disable syncLog
systemctl daemon-reload
#systemctl enable syncLog

cat <<EOF

Installed successfully.

Please edit setting file:$ConfigFile , and execute following command.

'sudo systemctl enable syncLog'
'sudo systemctl start syncLog'

EOF


