# see: https://github.com/pages-themes/slate
theme: jekyll-theme-slate
repository: webdino/pizero-workshop
lang: ja
title: '<a href="/" style="color: white">Pi Zero Easy IoT</a>'
description: 安価で簡単に IoT を始めよう！ - Raspberry Pi Zero によるプログラミングレス IoT 環境データ収集
show_downloads: false
#google_analytics:
#include:
#  - _redirects

# configs for GitHub Pages defult plugins
# https://help.github.com/en/articles/configuring-jekyll-plugins
# https://github.com/benbalter/jekyll-readme-index
readme_index:
  remove_originals: true

# Use CommonMarkGhPages for Markdown parser (after v172)
# https://github.com/github/jekyll-commonmark-ghpages
# https://github.com/github/pages-gem/releases/tag/v172
markdown: CommonMarkGhPages
commonmark:
  options:
    - FOOTNOTES
    - TABLE_PREFER_STYLE_ATTRIBUTES
  extensions:
    - strikethrough
    - autolink
    - table

# Polyglot: Multilingual (i18n) support
# https://github.com/untra/polyglot
languages: ["ja", "en"]
default_lang: "ja"
exclude_from_localization: ["assets", "images"]
parallel_localization: true
